name: Deploy to Google Cloud [backend]
on: [ push, pull_request ]

env:
  GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  GCLOUD_REGION: europe-west3
  GCLOUD_GCR: eu.gcr.io

jobs:
  GCLOUD_DEPLOY:
    if: ${{ contains(github.event.head_commit.message, '[GCLOUD]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-test-
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          version: '437.0.1'
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
      - name: Build
        run: |
          ./gradlew ktor-server:umbrella:clean ktor-server:umbrella:shadowJar
      - name: Deploy
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          GCE_INSTANCE: instance-1
          GCE_INSTANCE_ZONE: us-east1-b
        run: |
          gcloud compute scp --zone us-east1-b ./ktor-server/umbrella/build/libs/umbrella-all.jar alexzhirkevich@instance-1:app.jar
          gcloud compute ssh --zone us-east1-b alexzhirkevich@instance-1 --command './run.sh'
        shell: bash
