name: Deploy to Firebase Hosting [frontend]
on: [ push, pull_request ]
jobs:
  WEBAPP_DEPLOY:
    if: ${{ contains(github.event.head_commit.message, '[WEB]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          ./gradlew webApp:jsBrowserWebpack
      - name: Webpack
        run: |
          chmod +x ./webApp/webpack.sh
          ./webApp/webpack.sh distributions
          cp -r webApp/build/distributions/* webApp/public
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_B0TCREATOR }}'
          projectId: ${{ secrets.GCLOUD_PROJECT_ID }}
          entryPoint: webApp
          channelId: live